name: Deploy
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Tests pass
        run: yarn test
      - name: Build list
        run: yarn build
      - name: Pin to IPFS
        id: upload
        uses: anantaramdas/ipfs-pinata-deploy-action@v1.6.3
        with:
          pin-name: Koyo Finance Default Token List
          path: "build/koyo-default.tokenlist.json"
          pinata-api-key: ${{ secrets.PINATA_API_KEY }}
          pinata-secret-api-key: ${{ secrets.PINATA_API_SECRET_KEY }}
      - name: Copy assets into sync folder
        run: |
          cp -R ./src/tokens ./sync
          cp ./build/koyo-default.tokenlist.json ./sync/koyo-default.tokenlist.json
          cp ./build/koyo-default.tokenlist.json ./sync/all.json

          mkdir -p ./sync/logos
          cp -R ./token-icons/* ./sync/logos

          mkdir -p ./sync/wallets
          cp -R ./wallets-icons/* ./sync/wallets

          mkdir -p ./sync/chains
          cp -R ./chains-icons/* ./sync/chains

          mkdir -p ./sync/token-lists
          cp -R ./token_list-logos/* ./sync/token-lists
      - name: Upload assets
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete --exclude '.gitkeep'
        env:
          AWS_S3_BUCKET: ${{ secrets.R2_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          AWS_S3_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
          AWS_REGION: "us-east-1"
          SOURCE_DIR: "sync"
