name: Upload assets
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/upload.yaml'
      - 'src/tokens/**'
      - 'token-icons/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Copy assets into sync folder
      run: |
        cp -R ./src/tokens ./sync

        mkdir -p ./sync/logos
        cp -R ./token-icons/* ./sync/logos
    - name: Upload assets
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --follow-symlinks --delete --exclude '.gitkeep'
      env:
        AWS_S3_BUCKET: ${{ secrets.R2_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
        AWS_S3_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
        AWS_REGION: 'us-east-1'
        SOURCE_DIR: 'sync'
